steps:
  - name: 'python:3.12'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        apt-get update --no-install-recommends && apt-get install -y yq yamllint
        pip install --user pyyaml 
        python /workspace/generate_cloudbuild.py
        cat /workspace/cloudbuild_generated.yaml | yq 
    env:
      - 'WORKSPACES=${_WORKSPACES}'
      - 'TF_VERSION=${_TF_VERSION}'

  # - name: 'golang'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       go mod init github.com/username/cloudbuild-generator
  #       go get gopkg.in/yaml.v3
  #       _PR_NUMBER=${_PR_NUMBER} go run generate_cloudbuild.go

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud builds submit https://github.com/$REPO_FULL_NAME \
          --config=/workspace/cloudbuild_generated.yaml \
          --region=$LOCATION \
          --git-source-revision=$BRANCH_NAME \
          --substitutions=^:^BRANCH_NAME=$BRANCH_NAME:_PR_NUMBER=${_PR_NUMBER}

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       gcloud builds submit https://github.com/$REPO_FULL_NAME \
  #         --config=/workspace/go_cloudbuild_generated.yaml \
  #         --region=$LOCATION \
  #         --git-source-revision=$BRANCH_NAME \
  #         --substitutions=BRANCH_NAME=$BRANCH_NAME

options:
  dynamicSubstitutions: true
  automapSubstitutions: true
substitutions:
  _TF_VERSION: '1.11'
  _WORKSPACES: 'gitops,dev'
  _PR_NUMBER: ''
# --dict-flag=^:^a=b,c:d=f,g # => {'a': 'b,c', 'd': 'f,g'}