apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kpack.fullname" . }}-build-waiter-image
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
data:
  image: {{ .Values.buildWaiterImage.image | quote }}