apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kpack.fullname" . }}-certs-admin-binding
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "kpack.fullname" . }}-certs-admin'
subjects:
- kind: ServiceAccount
  name: '{{ include "kpack.fullname" . }}-webhook'
  namespace: '{{ .Release.Namespace }}'