apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kpack.fullname" . }}-config-logging
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
data:
  zap-logger-config: {{ .Values.configLogging.zapLoggerConfig | toYaml | indent 1
    }}