apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kpack.fullname" . }}-defaults.webhook.kpack.io
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kpack.fullname" . }}-
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "kpack.fullname" . }}-kpack-webhook'
      namespace: '{{ .Release.Namespace }}'
  failurePolicy: Fail
  matchPolicy: Exact
  name: defaults.webhook.kpack.io
  sideEffects: None