apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "kpack.fullname" . }}-kpack-build-high-priority
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
description: High priority class for kpack builds triggered by user changes.
globalDefault: false
value: 1000