apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kpack.fullname" . }}-kpack-controller-admin-binding
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kpack.fullname" . }}-kpack-controller-admin'
subjects:
- kind: ServiceAccount
  name: '{{ include "kpack.fullname" . }}-controller'
  namespace: '{{ .Release.Namespace }}'