apiVersion: v1
kind: Service
metadata:
  name: {{ include "kpack.fullname" . }}-kpack-webhook
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kpackWebhook.type }}
  selector:
    role: webhook
  {{- include "kpack.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.kpackWebhook.ports | toYaml | nindent 2 }}