apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "kpack.fullname" . }}-kpack-build-low-priority
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
description: Low priority class for kpack builds triggered by operator changes.
globalDefault: false
preemptionPolicy: Never
value: 1