apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kpack.fullname" . }}-rebase-image
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
data:
  image: {{ .Values.rebaseImage.image | quote }}