apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kpack.fullname" . }}-controller
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kpack.fullname" . }}-webhook
  labels:
  {{- include "kpack.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.webhook.serviceAccount.annotations | nindent 4 }}