{{ range .Values.serviceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  selector:
    matchLabels:
      kubernetes.io/name: {{ .name }}
    {{- if .serviceSelector }}
      {{ toYaml .serviceSelector | nindent 6 }}
    {{- end }}
  endpoints:
  - port: {{ (default 8080 .servicePort) | quote }}
  namespaceSelector:
    any: true
{{-  end }}