prometheus:
  prometheusSpec:
    image:
      # tag: v2.51.1
    replicas: 3
    topologySpreadConstraints: 
    - maxSkew: 1
      topologyKey: cloud.google.com/gke-nodepool
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    storageSpec: 
     volumeClaimTemplate:
       spec:
        #  storageClassName: premium-rwo
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 10Gi

    externalLabels:
      cluster: my-cluster-name
    tolerations:
     - key: "key"
       operator: "Equal"
       value: "value"
       effect: "NoSchedule"