apps:
  prometheus:
    url: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    chart: kube-prometheus-stack
    version: 80.4.1
    values: 
      alertmanager:
        alertmanagerSpec:
          replicas: 2
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 500Mi
          storageSpec:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 5Gi
      grafana:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            memory: 500Mi
        additionalDataSources:
          - name: Loki
            access: proxy
            orgId: 1
            type: loki
            jsonData:
              tlsSkipVerify: true
            url: http://loki-stack.logging.svc.cluster.local:3100
            version: 1
      prometheus:
        prometheusSpec:
          replicas: 2
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 2Gi
          storageSpec:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 10Gi
      prometheusOperator:
        enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            memory: 500Mi
        admissionWebhooks:
          patch:
            podAnnotations:
              sidecar.istio.io/inject: "false"

  vpa:
    url: https://charts.fairwinds.com/stable
    namespace: vpa
    chart: vpa
    version: 4.10.0
    values:
      podLabels:
        sidecar.istio.io/inject: "false"
      recommender:
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            memory: 500Mi
      updater:
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            memory: 500Mi
      admissionController:
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            memory: 500Mi

  bookinfo:
    url: https://charts.fairwinds.com/stable
    namespace: bookinfo
    chart: bookinfo
    version: 0.1.0
  cert-manager:
    url: https://charts.jetstack.io
    namespace: cert-manager
    chart: cert-manager
    version: 1.19.2
    disable_istio: true
    values:
      installCRDs: true
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          memory: 500Mi
      webhook:
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            memory: 200Mi
      cainjector:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            memory: 500Mi
