apps:
  prometheus:
    url: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    chart: kube-prometheus-stack
    version: 58.2.0
    values: 
      alertmanager:
        alertmanagerSpec:
          replicas: 7
