apps:
  prometheus:
    url: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    chart: kube-prometheus-stack
    version: 57.2.0
  vpa:
    url: https://charts.fairwinds.com/stable
    namespace: vpa
    chart: vpa
    version: 4.4.6
  bookinfo:
    url: https://charts.fairwinds.com/stable
    namespace: bookinfo
    chart: bookinfo
    version: 0.1.0
  cert-manager:
    url: https://charts.jetstack.io
    namespace: cert-manager
    chart: cert-manager
    version: 1.14.5