name: prometheus-monitoring
chart: kube-prometheus-stack
repoURL: https://prometheus-community.github.io/helm-charts
targetRevision: "82.10.3"
namespace: monitoring
cluster_env: gitops
helm:
  values:
    alertmanager:
      alertmanagerSpec:
        replicas: 2
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 5Gi
    grafana:
      additionalDataSources:
        - name: Loki
          access: proxy
          orgId: 1
          type: loki
          jsonData:
            tlsSkipVerify: true
          url: http://loki-stack.logging.svc.cluster.local:3100
          version: 1
    prometheus:
      prometheusSpec:
        replicas: 2
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 10Gi
    prometheusOperator:
      enabled: true
      admissionWebhooks:
        patch:
          podAnnotations:
            sidecar.istio.io/inject: "false"
