applicationsets:
  %{~ for cluster_name, cluster in clusters ~}
  ${cluster_name}-apps:
    namespace: argocd
    generators:
    - git:
        repoURL: https://github.com/muyisbox/gke.git
        revision: master
        files:
        - path: gke-applications/${cluster_name}/*.yaml
    template:
      metadata:
        name: '{{.name}}-${cluster_name}'
        namespace: argocd
        labels:
          app.kubernetes.io/name: '{{.name}}'
          app.kubernetes.io/managed-by: argocd
          dynamou.io/cluster: ${cluster_name}
          dynamou.io/env: '{{.cluster_env}}'
        finalizers:
        - resources-finalizer.argocd.argoproj.io
      spec:
        project: project-${cluster_name}
        source:
          repoURL: '{{.repoURL}}'
          targetRevision: '{{.targetRevision}}'
          chart: '{{.chart}}'
          helm:
            releaseName: '{{.name}}'
        destination:
          name: ${cluster_name}-cluster
          namespace: '{{.namespace}}'
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          managedNamespaceMetadata:
            labels:
              istio.io/rev: stable
    syncPolicy:
      applicationsSync: sync
    goTemplate: true
    templatePatch: |
      spec:
        source:
          {{- if .helm }}
          helm:
            releaseName: '{{.name}}'
            {{- if .helm.values }}
            valuesObject:
              {{- toYaml .helm.values | nindent 14 }}
            {{- end }}
            {{- if .helm.valueFiles }}
            valueFiles:
              {{- range $f := .helm.valueFiles }}
              - {{ $f }}
              {{- end }}
            {{- end }}
          {{- end }}
  %{~ endfor ~}

projects:
  %{~ for cluster_name, cluster in clusters ~}
  project-${cluster_name}:
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    description: Project for ${cluster_name} cluster
    sourceRepos:
    - '*'
    destinations:
    - name: ${cluster_name}-cluster
      namespace: '*'
      server: https://${cluster.endpoint}
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  %{~ endfor ~}
