apps:
  applications: 
  %{ for app in apps }
    ${app.name}:
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      project: ${app.project}
      source:
        repoURL: ${app.repoURL}
        targetRevision: ${app.targetRevision}
        chart: ${app.chart}
        helm:
          releaseName: ${app.name}
          values: ${app.values}
      destination:
        server: https://kubernetes.default.svc
        namespace: ${app.namespace}
      syncPolicy:
        managedNamespaceMetadata:
          labels: # The labels to set on the application namespace
            istio.io/rev: stable
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
  %{ endfor }
  projects: 
    boeing:
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      description: A Sample Project to Deploy applications into Boing Clusters
      sourceRepos:
      - '*'
      destinations:
      - name: '*'
        namespace: '*'
        server: https://kubernetes.default.svc
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    - name: sammy
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      description: A Sample Project to Deploy applications into Boing Clusters
      sourceRepos:
      - '*'
      destinations:
      - name: '*'
        namespace: '*'
        server: https://kubernetes.default.svc
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'


