applications:
  %{~ for k, app in apps ~}
  ${k}:
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: ${app.project}
    source:
      repoURL: ${app.repoURL}
      targetRevision: ${app.targetRevision}
      chart: ${app.chart}
      helm:
        releaseName: ${app.name}
        values: ${app.values}
    destination:
      server: ${app.dest_server}
      namespace: ${app.namespace}
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          istio.io/rev: stable
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  %{~ endfor ~}
projects:
  %{~ for cluster_name, cluster in clusters ~}
  project-${cluster_name}:
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    description: Project for ${cluster_name} cluster
    sourceRepos:
    - '*'
    destinations:
    - name: ${cluster_name}-cluster
      namespace: '*'
      server: https://${cluster.endpoint}
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  %{~ endfor ~}
