---
alertmanager:
  alertmanagerSpec:
    replicas: 2
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi
grafana:
  additionalDataSources:
    - name: Loki
      access: proxy
      orgId: 1
      type: loki
      jsonData:
        tlsSkipVerify: true
      url: http://loki-stack.logging.svc.cluster.local:3100
      version: 1
prometheus:
  prometheusSpec:
    replicas: 2
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
prometheusOperator:
  enabled: true
  admissionWebhooks:
    patch:
      podAnnotations:
        sidecar.istio.io/inject: "false"
