---
# Reloader 2.x values
watchGlobally: true
readOnlyRootFilesystem: true

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 128Mi

serviceMonitor:
  enabled: true
  labels:
    release: prometheus-monitoring
