---
# Metrics Server values
replicas: 2

args:
  - --kubelet-preferred-address-types=InternalIP

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus-monitoring
