---
# External Secrets Operator 2.x values
crds:
  install: true

replicaCount: 2

serviceMonitor:
  enabled: true
  labels:
    release: prometheus-monitoring

webhook:
  replicaCount: 1

certController:
  replicaCount: 1
