---
# External Secrets Operator values
installCRDs: true

replicaCount: 2

serviceMonitor:
  enabled: true
  labels:
    release: prometheus-monitoring

webhook:
  replicaCount: 1

certController:
  replicaCount: 1
