module:
  example-module:
    source: "hashicorp/consul/aws"
    version: "0.0.1"
    organization: "your-org"
    workspace:
      id: "ws-xxxxxxx"
    description: "Managed by Kubernetes"  # Optional
    executionMode: "remote"               # Optional
    applyMethod: "auto"                   # Optional
    allowDestroyPlan: false               # Optional
    remoteStateSharing: false             # Optional
    variables:
      - key: "region"
        value: "us-west-1"
    outputs:
      - key: "instance_id"
    token:
      secretKeyRef:
        name: "terraform-api-token"
        key: "token"
    environment: "development"            # Optional
    notifications: []                     # Optional
    runTasks: []                          # Optional
    runTriggers: []                       # Optional
    project: ""                           # Optional
    sshKeyID: ""                          # Optional

workspaces:
  workspace1:
    name: "example-workspace-1"
    organization: "your-org"
    applyMethod: "auto"
    autoApply: true
    description: "A workspace for managing production infrastructure"
    executionMode: "remote"
    queueAllRuns: false
    speculativeEnabled: true
    terraformVersion: "1.0.0"
    allowDestroyPlan: false
    project: "Project A"
    remoteStateSharing: true
    tags:
      - "production"
      - "managed"
    teamAccess:
      - name: "teamA"
        access: "read"
    versionControl:
      repoPath: "git@github.com:your-org/terraform-repo.git"
      branch: "main"
      ingressSubmodules: true
      workingDirectory: "prod"
    sshKey: "ssh-rsa AAAAB3..."
    environmentVariables:
      - name: "AWS_ACCESS_KEY_ID"
        valueFrom:
          secretKeyRef:
            name: "aws-keys"
            key: "access_key"
    notifications:
      - name: "slack-notification"
        enabled: true
        destinationType: "slack"
        address: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
        token: "xoxb-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxx"
    runTasks:
      - name: "task1"
    runTriggers:
      - name: "trigger1"
    terraformVariables:
      - name: "instance_type"
        value: "t2.large"
        sensitive: false
