apiVersion: v2
name: argocd-applications
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: argo-cd
    version: 6.7.6
    repository: https://argoproj.github.io/argo-helm
    alias: argocd
    condition: argocd.enabled
